export const games = [
  {
    id: 1,
    platforms: ["playstation", "pc", "xbox"],
    metacritic: 80,
    name: "Jogo A",
    release_date: "Feb 25, 2022",
    genres: ["Action", "RPG"],
  },
  {
    id: 2,
    platforms: ["playstation"],
    metacritic: 50,
    name: "Jogo B",
    release_date: "Apr 10, 2022",
    genres: ["RPG"],
  },
  {
    id: 3,
    platforms: ["pc", "xbox"],
    metacritic: 30,
    name: "Jogo C",
    release_date: "Jan 25, 2022",
    genres: ["Action", "Puzzle"],
  },
  {
    id: 4,
    platforms: ["xbox"],
    metacritic: 70,
    name: "Jogo D",
    release_date: "May 10, 2022",
    genres: ["Action", "RPG"],
  },
  {
    id: 5,
    platforms: ["playstation", "pc", "xbox"],
    metacritic: 10,
    name: "Jogo E",
    release_date: "Dez 2, 2022",
    genres: ["Action", "RPG"],
  },
  {
    id: 6,
    platforms: ["nintendo", "xbox"],
    metacritic: 30,
    name: "Jogo F",
    release_date: "Dez 9, 2022",
    genres: ["Action", "RPG"],
  },
];
