export const games = [
  {
    id: 1,
    platforms: ["playstation", "pc", "xbox"],
    metacritic: 80,
    name: "Jogo A",
    release_date: "2022-01-20",
    genres: ["Action", "RPG"],
  },
  {
    id: 2,
    platforms: ["playstation"],
    metacritic: 50,
    name: "Jogo B",
    release_date: "2019-11-15",
    genres: ["RPG"],
  },
  {
    id: 3,
    platforms: ["pc", "xbox"],
    metacritic: 30,
    name: "Jogo C",
    release_date: "2021-12-01",
    genres: ["Action", "Puzzle"],
  },
  {
    id: 4,
    platforms: ["xbox"],
    metacritic: 70,
    name: "Jogo D",
    release_date: "2020-05-30",
    genres: ["Action", "RPG"],
  },
  {
    id: 5,
    platforms: ["playstation", "pc", "xbox"],
    metacritic: 10,
    name: "Jogo E",
    release_date: "2022-10-15",
    genres: ["Action", "RPG"],
  },
  {
    id: 6,
    platforms: ["nintendo", "xbox"],
    metacritic: 30,
    name: "Jogo F",
    release_date: "2021-01-17",
    genres: ["Action", "RPG"],
  },
];
